{
  "height": 20,
  "width": 30,
  "grid": [
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      }
    ],
    [
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 4
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 1
      }
    ],
    [
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 4
      }
    ],
    [
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 5
      }
    ],
    [
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      }
    ],
    [
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 5
      }
    ],
    [
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 1
      }
    ],
    [
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 5
      }
    ],
    [
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      },
      {
        "type": 0
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 4
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 4
      },
      {
        "type": 4
      },
      {
        "type": 5
      },
      {
        "type": 5
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 5
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 1
      },
      {
        "type": 5
      },
      {
        "type": 2,
        "color": "#FF0000",
        "load_cap": 10,
        "battery_cap": 1000,
        "ip": ""
      },
      {
        "type": 0
      },
      {
        "type": 5
      },
      {
        "type": 1
      },
      {
        "type": 4
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 3,
        "item_number": 1,
        "quantity": 10,
        "weight": 1
      },
      {
        "type": 0
      }
    ]
  ]
}