{
  "height": 10,
  "width": 17,
  "grid": [
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ],
    [
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      },
      {
        "type": 0
      }
    ]
  ]
}