// Menu tiles
LEFT_MENU = {
    EMPTY: 0,
    TEMPS: 1,
    MAP: 2,
    ENTRY: 3,
    ROBOT: 4,
    RACK: 5,
    PARK: 6,
    OBSTACLE: 7,
    ORDER: 8
};

RIGHT_MENU = {
    EMPTY: 0,
    LOGS: 1,
    STATS: 2
};

// Running modes
RUNNING_MODE = {
    DESIGN: 0,
    SIMULATE: 1,
    DEPLOY: 2
};

// Map
MAP_INIT_WIDTH = 17;
MAP_INIT_HEIGHT = 10;
MAP_CELL = {
    EMPTY: 0,
    ENTRY: 1,
    ROBOT: 2,
    RACK: 3,
    PARK: 4,
    OBSTACLE: 5
};

// Shouting codes
SHOUT_RUNNING_MODE = 0;
// SHOUT_MAP_SIZE_CHANGED = 1;
SHOUT_MAP_TEMP_APPLIED = 2;
SHOUT_ERROR = 3;
SHOUT_GRID_CLICK = 3;
SHOUT_GRID_DRAG = 4;

// Logs levels
LOG_LEVEL_INFO = 0;
LOG_LEVEL_WARNING = 1;
LOG_LEVEL_ERROR = 2;

LOG_OBJECT_ROBOT = 0;
LOG_OBJECT_RACK = 1;
LOG_OBJECT_ORDER = 2;
LOG_OBJECT_SIMULATION = 3;